Feb 2015, J. Slavič in L.Knez

Vprašanje 1: Naredite slovar lokalno nameščenih modulov (uporabite izpeljevanje slovarjev, key naj bo ime modula, vrednost naj bo verzija).

In [7]:
import pip
#moduli_vsi = {print(i.key) for i in pip.get_installed_distributions()}

moduli_vsi = {i.key: i.version for i in pip.get_installed_distributions()}

moduli_vsi


{'lxml': '3.4.0',
 'binstar': '0.7.1',
 'nose': '1.3.4',
 'jinja2': '2.7.3',
 'pycparser': '2.10',
 'statsmodels': '0.5.0',
 'multipledispatch': '0.4.7',
 'pyside': '1.2.2',
 'decorator': '3.4.0',
 'pyyaml': '3.11',
 'rope-py3k': '0.9.4-1',
 'sympy': '0.7.5',
 'pygments': '1.6',
 'python-dateutil': '2.1',
 'mock': '1.0.1',
 'scipy': '0.14.0',
 'sqlalchemy': '0.9.7',
 'jdcal': '1.0',
 'numba': '0.14.0',
 'psutil': '2.1.1',
 'youtube-dl': '2015.02.19.2',
 'networkx': '1.9.1',
 'colorama': '0.3.1',
 'nltk': '3.0.0',
 'py': '1.4.25',
 'cryptography': '0.5.4',
 'markupsafe': '0.23',
 'menuinst': '1.0.4',
 'sockjs-tornado': '1.0.1',
 'blz': '0.6.2',
 'pyparsing': '2.0.1',
 'pillow': '2.7.0',
 'spyder': '2.3.1',
 'pywin32': '219',
 'llvmpy': '0.12.7',
 'numpy': '1.9.0',
 'pytest': '2.6.3',
 'conda-build': '1.8.2',
 'docutils': '0.12',
 'tables': '3.1.1',
 'pytz': '2014.7',
 'scikit-learn': '0.15.2',
 'bokeh': '0.6.1',
 'basemap': '1.0.8',
 'astropy': '0.4.2',
 'h5py': '2.3.1',
 'pandas': '0.1

Vprašanje 2: S pomočjo slovarja iz prejšnje točke čimbolj elegantno preverite ali so nameščeni sledeči moduli: ['numpy', 'scipy', 'matplotlib', 'pandas', 'pyjamas'].

In [7]:
moduli_iskani = {'numpy', 'scipy', 'matplotlib', 'pandas', 'pyjamas'}  # Naredim množico

# Izpišejo se le tisti moduli, ki so naloženi (primerjamo obe množici, uporabimo and)
moduli_vsi.keys() & moduli_iskani

{'matplotlib', 'numpy', 'pandas', 'scipy'}

Vprašanje 3: Namestite poljubni modul iz https://pypi.python.org/pypi in ga preizkusite. Na vajah izpustimo.

Vprašanje 4: Pretvorite *navaden* Python seznam v ``numpy`` seznam. Preverite tip enega in drugega.

In [3]:
matrika = [[1, 2, 3],
           [4, 5, 6]]

In [4]:
type(matrika)

list

In [5]:
import numpy as np
matrika = np.asarray(matrika)
type(matrika)

numpy.ndarray

In [7]:
matrika

array([[1, 2, 3],
       [4, 5, 6]])

Vprašanje 5: Raziščite funkcije: ``np.ones``, ``np.zeros_like``, ``np.arange``, ``np.linspace`` (ali zadnja funkcija lahko vrne korak?).

In [8]:
a = np.ones((3, 2), dtype='complex')  
a

array([[ 1.+0.j,  1.+0.j],
       [ 1.+0.j,  1.+0.j],
       [ 1.+0.j,  1.+0.j]])

In [9]:
b = np.zeros_like(a)  # Vrne ničelno matriko z enako enako velikostjo in tipom spremenljivk
b

array([[ 0.+0.j,  0.+0.j],
       [ 0.+0.j,  0.+0.j],
       [ 0.+0.j,  0.+0.j]])

In [13]:
c = np.arange(10, 100, 2)    # np.arrange(zacetek, konec, korak) , konca ne vrne
c

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76,
       78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [14]:
d = np.linspace(0, 1, 11)   # linspace glede na trenutno definicijo poda 11 enakomerno oddaljenih točk
d

array([ 0. ,  0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9,  1. ])

In [15]:
d, step = np.linspace(0, 1, 11, retstep=True)  # Vrne tudi korak
step

0.1

Vprašanje 6: Prikažite uporabo rezanja.

In [16]:
d  

array([ 0. ,  0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9,  1. ])

In [17]:
d[::-1]  # Od zadnje do prve

array([ 1. ,  0.9,  0.8,  0.7,  0.6,  0.5,  0.4,  0.3,  0.2,  0.1,  0. ])

In [18]:
d[::2]  # Od prve do zadnje s korakom 2

array([ 0. ,  0.2,  0.4,  0.6,  0.8,  1. ])

In [19]:
d[4:] # Od 4 do konca

array([ 0.4,  0.5,  0.6,  0.7,  0.8,  0.9,  1. ])

In [20]:
d[1:] # Od 1 do konca

array([ 0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9,  1. ])

In [21]:
d[3:7] # Od 3 do 7 - pazi zadnjega! Polzaprt interval

array([ 0.3,  0.4,  0.5,  0.6])

Vprašanje 7: Prikažite razliko med vrstičnim in stolpčnim vektorjem. Prikažite tipične matematične operacije med vektorji in matrikami.

In [22]:
# Vrstični vektor
a = np.asarray([1, 2, 3])
print(a)

# Stolpični vektor
b = np.ones((3, 1))
print(b)

# Naredimo še matriko
A = np.array([[1, 2, 1], [3, 2, 1], [1, 7, 3]])
print(A)

# Transponiramo matriko
B = A.transpose()
print(B)

[1 2 3]
[[ 1.]
 [ 1.]
 [ 1.]]
[[1 2 1]
 [3 2 1]
 [1 7 3]]
[[1 3 1]
 [2 2 7]
 [1 1 3]]


In [23]:
# Nekaj operacij:
print(A*B)

print(a*B)

print(np.dot(a, A)) 

print(np.cross(a, B))


[[1 6 1]
 [6 4 7]
 [1 7 9]]
[[ 1  6  3]
 [ 2  4 21]
 [ 1  2  9]]
[10 27 12]
[[-7  2  1]
 [ 8 -1 -2]
 [ 3  0 -1]]


Vprašanje 8: Ustvarite matriko ničel dimenzije 3 x 2 in drugi stolpec zapolnite z vektorjem enic.

In [24]:
C = np.zeros((3, 2))
C[:, 1] = 1
C

array([[ 0.,  1.],
       [ 0.,  1.],
       [ 0.,  1.]])

Vprašanje 9: Ustvarite enotsko matriko dimenzije 5 podatkovnega tipa ``complex``.

In [25]:
I = np.identity(5, dtype=complex)
I

array([[ 1.+0.j,  0.+0.j,  0.+0.j,  0.+0.j,  0.+0.j],
       [ 0.+0.j,  1.+0.j,  0.+0.j,  0.+0.j,  0.+0.j],
       [ 0.+0.j,  0.+0.j,  1.+0.j,  0.+0.j,  0.+0.j],
       [ 0.+0.j,  0.+0.j,  0.+0.j,  1.+0.j,  0.+0.j],
       [ 0.+0.j,  0.+0.j,  0.+0.j,  0.+0.j,  1.+0.j]])

Vprašanje 10: Ustvarite matriko enic dimenzije ``N`` in izračunajte vsoto poljubnga stolpca. Poskusite najti najhitrejši in najelegantnejši (vektoriziran) način in ga primerjajte s pristopom v zanki. Namig: np.sum().

In [24]:
A = np.ones((1000,1000))

In [25]:
print(np.sum(A[:,1]))  # Sesteva po vseh vrsticah, po drugem stolpcu

1000.0


In [26]:
%timeit np.sum(A[:,1]) 

100000 loops, best of 3: 16.5 µs per loop


In [27]:
out = 0.               # Bere vrstico po vrstico in nato sešteva drugi element (to je seveda drugi stolpec)
for vrstica in A:
    out += vrstica[1]
    
out

1000.0

In [28]:
%%timeit
out = 0.
for vrstica in A:
    out += vrstica[1]

1000 loops, best of 3: 337 µs per loop
